seed: 111
env_init_seed: 1
eval_init_seed: 2

num_train_steps: 1000000
num_envs: 16

agent:
  learning_rate: 3e-4
  eps_exploration: 0.00
  train_backward: false

network:
  # Input size and output size are computed based on the environment
  hidden_size: 256
  depth: 2

logging:
  track_each: 500 # in terms of total training steps, not divited by num_envs
  metric_buffer_size: 1000000
  tqdm_print_rate: 20
  use_wandb: False

# Technical information for wandb
wandb:
  entity: gfn-sampling
  project: mctx

# Technical information for hydra
hydra:
  run:
    dir: ./tmp/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: ./tmp/${now:%Y-%m-%d}/${now:%H-%M-%S}