seed: 111
env_seed: 1
eval_seed: 2

num_train_steps: 10000
num_envs: 1

agent:
  learning_rate: 3e-4
  eps_exploration: 0.00
  train_backward: false

network:
  num_layers: 3
  mlp_num_layers: 1
  embedding_size: 128
  num_heads: 4

environment:
  samples_path: "data/lin-gauss.npy"
  
  prior:
    _target_: gfnx.reward.UniformDAGPrior
  
  likelihood:
    _target_: gfnx.reward.LinearGaussianScore
    prior_mean: 0.0
    prior_scale: 1.0
    obs_scale: 0.316  # sqrt(0.1)

metrics:
  num_traj: 512
  batch_size: 16

logging:
  track_each: 500
  tqdm_print_rate: 1
  use_wandb: False

# Technical information for wandb
wandb:
  entity: null  # Users default entity
  project: gfnx

# Technical information for hydra
hydra:
  run:
    dir: ./tmp/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: ./tmp/${now:%Y-%m-%d}/${now:%H-%M-%S}